name: End-toend tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubunto-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v2